[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
poem-ratelimit = { path = "../.." }

tokio = { version = "1.17", features = ["rt-multi-thread"] }
redis = { version = "0.27", features = ["tokio-comp", "connection-manager"] }
poem = "3.1.5"
serde_yaml = "0.9"
